### ISSUE TITLE
Please add conf.json

### ISSUE THREAD

**Issue by garikZubov** [herrBez/Nduja#81]
Hello, can you add conf.json(it seems to be deleted) to repo or explain how I should write it, please.

There's my console output:
root@ubuntu:/home/beagle/Nduja-master# python3 Nduja
Tasks is   0
Config is  conf.json
Logging is  20
ERROR:root:Configuration file not found
root@ubuntu:/home/beagle/Nduja-master# python3 Nduja -h
python3.5 Nduja -t <tasks> -c <conf_file>
<task> could be:
	* 0 performs all tasks
	* 1 performs wallet search
	* 2 performs user info search
	* 3 performs 1 and 2
default <conf_file> is "./Nduja/conf.json"

root@ubuntu:/home/beagle/Nduja-master# cd Nduja/
root@ubuntu:/home/beagle/Nduja-master/Nduja# ls
address_checkers  graph        __pycache__               user_info_retriever
dao               __init__.py  result_parser             utility
db                __main__.py  suspect_transactions.txt  wallet_collectors
root@ubuntu:/home/beagle/Nduja-master/Nduja#

**Comment by herrBez** [comment]
I am glad your are interested in this project. I added a reference configuration file and the instruction on how to configure it properly.

**Comment by garikZubov** [comment]
Thank you very much. Your project is definitly one of the most profound and interesting.
